/**
 * Created by Fraser Lewis-Smith on 22/08/2017.
 */
public enum Group {
    FINANCIAL_ANALYSIS, PROJECT_MANAGEMENT, STRATEGY, OPERATIONS, TECHNOLOGY, HUMAN_CAPITAL, SOFTWARE, TEACHING_AND_TRAINING, BUSINESS_DEVELOPMENT, MARKETING_AND_SALES
}
